bots:
  - id: main_bot
    pair: ETH-PERP      # Options: BTC-PERP, ETH-PERP, SOL-PERP
    dex_a: vest
    dex_b: paradex
    spread_entry: 0.25
    spread_exit: -0.05
    leverage: 50
    position_size: 0.3  # BTC: 0.02 | ETH: 0.1 | SOL: 1.0

api:
  port: 8080
  ws_heartbeat_sec: 30
